export const ADD_STAFFS = 'ADD_STAFFS';
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';
export const ADD_STAFF = 'ADD_STAFF';
export const REMOVE_STAFF = 'REMOVE_STAFF';

export const ADD_DEPARTMENTS = 'ADD_DEPARTMENTS';
export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';

export const GET_STAFFSDEPA = 'GET_STAFFSDEPA';
export const STAFFSDEPA_LOADING = 'STAFFSDEPA_LOADING';
export const STAFFSDEPA_FAILED = 'STAFFSDEPA_FAILED';

export const ADD_SALARIES = 'ADD_SALARIES';
export const SALARIES_LOADING = 'SALARIES_LOADING';
export const SALARIES_FAILED = 'SALARIES_FAILED';

export const TOGGLE_MODAL = 'TOGGLE_MODAL';
